baseurl = "http://hillsideprojects.github.io/portfolio/"
languageCode = "en-us"
title = "Hillside Projects"
theme = "casper"
paginate = 5
DisqusShortname = "hillsideprojects"
Copyright = "c/o Mennerdahl | Barnängsgatan 58 | 11641 Stockholm, Sweden | All rights reserved - 2016"
canonifyurls = true
builddrafts = false

[params]
  description = "A research/production group formed by Emily Mennerdahl and Jonas Böttern."
  cover = "images/european_roller_performance.jpeg"
  author = "© Hillside Projects"
  authorlocation = "Stockholm, Sweden"
  authorwebsite = "mailto: info@hillsideprojects.se"
  bio= ""
  logo = "images/logo.gif"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  # githubName = ""
  # vimeoName = ""
  # facebookName = "HillsideProjects"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
[permalinks]
  post = "/:slug/"
[sitemap]
  ChangeFreq = ""
  Filename = "sitemap.xml"
  Priority = "-1"
[[menu.main]]
    name = "News"
    weight = -120
    identifier = "news"
    url = "/"
[[menu.main]]
    name = "About"
    weight = -110
    identifier = "about"
    url = "/about"
